[tool.pytest.ini_options]
addopts = [
    "--cov=.",
    "--cov-config=pyproject.toml",
    "--cov-report=xml",
    "--cov-report=term-missing",
    "--doctest-modules",
    "--doctest-continue-on-failure",
    ]
python_files = ["tests.py", "test_*.py", "*_tests.py"]
filterwarnings = "ignore::DeprecationWarning"

[tool.coverage.run]
branch = true

[tool.coverage.report]
exclude_lines = [
    # Don't complain if non-runnable code isn't run:
    "if 0:",
    "if __name__ == .__main__.:",
    "if TYPE_CHECKING:",
]

omit = [
    "*/tests/*",
    "*/mocks/*",
    "*/tests.py",
    "venv/*",
    "site-packages",
]
sort = "Cover"

[tool.mypy]
python_version = "3.9"
disallow_untyped_defs = true
disallow_incomplete_defs = true
check_untyped_defs = true
disallow_untyped_decorators = true
ignore_missing_imports = true
follow_imports = "skip"
strict_optional = true

[[tool.mypy.overrides]]
module = [
    "tests.*",
    "venv.*",
    "site-packages.*"
]
ignore_errors = true

[tool.black]
line-length = 120
target-version = ['py39']
include = '\.pyi?$'
extend-exclude = '''
/(
    | docs
    | tests
)/
'''

[tool.isort]
include_trailing_comma = true
multi_line_output = 5
use_parentheses = true
atomic = true
ensure_newline_before_comments = true
line_length = 88
group_by_package = true
force_alphabetical_sort_within_sections = true
lexicographical = true
